### ISSUE TITLE
Frequency

### ISSUE THREAD

**Issue by MMAThijssen** [mmalekzadeh/motion-sense#2]
Hi, 

It is unclear to me with what frequency these signals were recorded. I am especially interested in accelerometer data. Can you clarify this, please?

Kind regards,

**Comment by mmalekzadeh** [comment]
Hey,
The sample rate is 50Hz. So, you have 50 sample points per seconds.

**Comment by MMAThijssen** [comment]
Thank you! 

I just found it in the article as well, so I will close the issue now.
