### ISSUE TITLE
Confusion about the userAcceleration data

### ISSUE THREAD

**Issue by crocodilegogogo** [mmalekzadeh/motion-sense#5]
Hi Mmalekzadeh,
    Recently I downloaded analysed the Motion-sense dataset, which has four kind of features, namely attitude, rotationRate, userAcceleration and the gravity. RotationRate readings are the readings of the gyroscope, gravity readings are acquired from the readings of the  accelerometer. However, I am confused whether the userAcceleration are the raw readings of the accelerometer, or the readings of linear acceleration (raw accelerometer readings minus the gravity readings). Please give me some advise!

                                                                                                   Looking forward for your reply!

**Comment by mmalekzadeh** [comment]
Hi @crocodilegogogo 

That `userAcceleration` shows the acceleration without the gravity force. So, in iOS, when you collect `accelerometer` data, the raw readings of the accelerometer are `userAcceleration+gravity `. 
Thus this `userAcceleration`  is raw accelerometer readings minus the gravity readings.

Please read this for more context: https://developer.apple.com/documentation/coremotion/cmdevicemotion
