### ISSUE TITLE
Question on Resolution

### ISSUE THREAD

**Issue by VivekSM1992** [mmalekzadeh/motion-sense#6]
Hello,

I couldn't find the resolution of the data on kaggle. I believe the data is in g. I assumed this as the resultant of GravityX,GravityY and GravityZ comes close to 1 and the gravity is 1g. However, in the other comment here it says 4096 LSB/g. I couldn't understand the comment.
 
Thank You!

**Comment by mmalekzadeh** [comment]
Hey @VivekSM1992 
As far as I know, the accelerometer of the iPhone 6 we used is this one:
https://www.bosch-sensortec.com/products/motion-sensors/accelerometers/bma280.html

- Resolution(in ±2g range): 0.244 mg
- Sensitivity (calibrated) : ±8 g

**Comment by VivekSM1992** [comment]
Thank You!
